<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="https://itg.santander.cl/CL/AppStorageProcedure3/SPSQLS/WSDL/wsCL1SPORAC-ACTMailComexCliente" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx0="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/PR_SCC_CLI_UPD_OPX.xsd" targetNamespace="https://itg.santander.cl/CL/AppStorageProcedure3/SPSQLS/WSDL/wsCL1SPORAC-ACTMailComexCliente">
    <import namespace="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/PR_SCC_CLI_UPD_OPX.xsd" location="../Resources/Schemas/PR_SCC_CLI_UPD_OPX.xsd"/>
    <message name="INPUT">
        <part element="pfx0:INPUT" name="parameters"/>
    </message>
    <message name="Response_PR_SCC_CLI_UPD_OPX">
        <part element="pfx0:Response_PR_SCC_CLI_UPD_OPX" name="parameters"/>
    </message>
    <message name="Response_PR_SCC_CLI_UPD_OPX2">
        <part element="pfx0:Response_PR_SCC_CLI_UPD_OPX" name="parameters"/>
    </message>
    <portType name="portType">
        <operation name="setMailComexCliente">
            <input message="tns:INPUT"/>
            <output message="tns:Response_PR_SCC_CLI_UPD_OPX"/>
            <fault name="fault1" message="tns:Response_PR_SCC_CLI_UPD_OPX2"/>
        </operation>
    </portType>
</definitions>