<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="https://itg.santander.cl/AppStoreProcedure3/Services/wsCL1SPORAC-CONListaTipoDocCategoria" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx0="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/SP_IDI_LST_TPO_DOC_CAT.xsd" targetNamespace="https://itg.santander.cl/AppStoreProcedure3/Services/wsCL1SPORAC-CONListaTipoDocCategoria">
    <import namespace="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/SP_IDI_LST_TPO_DOC_CAT.xsd" location="../Resources/Schemas/SP_IDI_LST_TPO_DOC_CAT.xsd"/>
    <message name="INPUT">
        <part element="pfx0:INPUT" name="parameters"/>
    </message>
    <message name="OUTPUT">
        <part element="pfx0:Response_SP_IDI_LST_TPO_DOC" name="parameters"/>
    </message>
    <portType name="portType">
        <operation name="getListaTipoDocCategoria">
            <input message="tns:INPUT"/>
            <output message="tns:OUTPUT"/>
        </operation>
    </portType>
</definitions>