<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:pfx0="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/PRTF_FM_DIAS_RETENCION.xsd" xmlns:tns="https://itg.santander.cl/AppStoreProcedure3/Services/wsCL1SPSQLS_CONRetencionOperacion" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="https://itg.santander.cl/AppStoreProcedure3/Services/wsCL1SPSQLS_CONRetencionOperacion">
    <import namespace="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/PRTF_FM_DIAS_RETENCION.xsd" location="../Resources/Schemas/PRTF_FM_DIAS_RETENCION.xsd"/>
    <message name="INPUT">
        <part element="pfx0:INPUT" name="parameters"/>
    </message>
    <message name="Response_PRTF_FM_DIAS_RETENCION">
        <part element="pfx0:Response_PRTF_FM_DIAS_RETENCION" name="parameters"/>
    </message>
    <portType name="portType">
        <operation name="getCONRetencionOperacion">
            <input message="tns:INPUT"/>
            <output message="tns:Response_PRTF_FM_DIAS_RETENCION"/>
        </operation>
    </portType>
</definitions>