<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:pfx0="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/SP_IDI_RGTRO_BZN.xsd" xmlns:tns="https://itg.santander.cl/CL/AppStorageProcedure3/1SPORAC/Process/wsCL1SPORAC-ALTRegistroBuzon" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="https://itg.santander.cl/CL/AppStorageProcedure3/1SPORAC/Process/wsCL1SPORAC-ALTRegistroBuzon">
    <import namespace="https://itg.santander.cl/AppStorageProcedure3/Resources/Schemas/SP_IDI_RGTRO_BZN.xsd" location="../Resources/Schemas/SP_IDI_RGTRO_BZN.xsd"/>
    <message name="INPUT">
        <part element="pfx0:INPUT" name="parameters"/>
    </message>
    <message name="OUTPUT">
        <part element="pfx0:Response_SP_IDI_RGTRO_BZN" name="parameters"/>
    </message>
    <portType name="portType">
        <operation name="setATLRegistroBuzon">
            <input message="tns:INPUT"/>
            <output message="tns:OUTPUT"/>
        </operation>
    </portType>
</definitions>