<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="https://itg.santander.cl/AppStoreProcedure3/Services/wsCL1SPORAC-CONDocumentosLegales" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:pfx0="http://www.tibco.com/schemas/AppStorageProcedure3/Resources/Schemas/SP_IDI_FLTRO_DOCTO.xsd" targetNamespace="https://itg.santander.cl/AppStoreProcedure3/Services/wsCL1SPORAC-CONDocumentosLegales">
    <import namespace="http://www.tibco.com/schemas/AppStorageProcedure3/Resources/Schemas/SP_IDI_FLTRO_DOCTO.xsd" location="../Resources/Schemas/SP_IDI_FLTRO_DOCTO.xsd"/>
    <message name="INPUT">
        <part element="pfx0:INPUT" name="parameters"/>
    </message>
    <message name="OUTPUT">
        <part element="pfx0:Response_SP_IDI_FLTRO_DOCTO" name="parameters"/>
    </message>
    <portType name="portType">
        <operation name="getDocumentosLegales">
            <input message="tns:INPUT"/>
            <output message="tns:OUTPUT"/>
        </operation>
    </portType>
</definitions>